### ISSUE TITLE
Segmentation fault when performing multiple analyses in same process

### ISSUE THREAD

**Issue by jbaayen** [Vitens/epynet#16]
epynet (probably the epanet library) crashes when creating and running two different networks after each other within the same process.

Steps to reproduce:
- Create an epynet network, run it
- Create another epynet, network, run it
- Segmentation fault

**Comment by michaeltryby** [comment]
@jbaayen what version of epanet library are you using? V2.1?

**Comment by jbaayen** [comment]
I'm using the binaries that are bundled with epynet master in the "lib" folder. It reports "20100" as version code.

**Comment by AbelHeinsbroek** [comment]
Hi Jorn,

Try using the 'multithreaded' branch, which should work as expected. However, only the Mac OS binary supports multithreading at the moment if I recall correctly.

**Comment by AbelHeinsbroek** [comment]
With the update to the EPANET 2.2 library this should be resolved.
