### ISSUE TITLE
epynet assumes IDs to be encoded using UTF-8

### ISSUE THREAD

**Issue by jbaayen** [Vitens/epynet#20]
`epanet2.py` makes extensive use of `str.decode()/encode()` to convert between string representations. Since no character set argument is provided, `decode()` will try to parse the provided bytes as UTF-8 and vice versa.

I am finding that the use of UTF-8 in EPANET files is certainly not universal. It would therefore be good if the character set would be configurable.

**Comment by AbelHeinsbroek** [comment]
I assume this can be closed with #21 ?

Thanks again for all the pull-requests. Would you mind updating the unit tests to cover the new functionality you've added?
