### ISSUE TITLE
Doesn't allow to change Node (reservoir) head.

### ISSUE THREAD

**Issue by nagpalh** [Vitens/epynet#30]
Hi,

I am wondering why the function ENsetnodevalue (epynet/epynet/epanet2.py) doesn't allow to change the head of the node?
I have a reservoir in my network and I want to change its total head value from epynet. 

Thanks

**Comment by AbelHeinsbroek** [comment]
you need to change the elevation (= head)

**Comment by nagpalh** [comment]
Thanks @AbelHeinsbroek.
