### ISSUE TITLE
Is it possible to change the total head at a reservoir instead of its elevation?

### ISSUE THREAD

**Issue by MarcDuQuesne** [Vitens/epynet#32]
Good morning,

I am working at [VORtech](https://www.vortech.nl/) on a project in a collaboration with Deltares and Vitens.
I am trying to simulate the flow of water using a model (for the gemeente Culemborg) at different times of the day.

I would like to change the total head at the reservoir. I saw that this can (effectively) be done by changing the elevation (static) property of the reservoir node, like this:

`nw.reservoirs[reservoir_name].set_static_property(EN_ELEVATION, value)`

but if my interpretation of the code is correct, I would ideally rather have:

`nw.reservoirs[reservoir_name].set_property(EN_HEAD, value)`

I also tried:
  `nw.reservoirs[reservoir_name].properties['head'] = value`

but this has no effect on the simulations (I guess because the self.set_object_value(code, value)) is not called.

**Comment by AbelHeinsbroek** [comment]
Hi,

The head is a computed ([read only](http://wateranalytics.org/EPANET/group___enumerations.html#gae538c7e564d9bd7c5a1f841b107c417d)) value, you can only change the elevation, which, together with the water level in the reservoirs, corresponds to the head.

Its easiest to change the elevation using:

```
nw.reservoirs[reservoir_name].elevation = value
```

https://github.com/Vitens/epynet/blob/master/tests/test_creation.py#L21
